In [ ]:
#!pip install numpy

In [2]:
import numpy as np

In [8]:
arr1 = np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
sum= np.sum(arr1)
mean = np.mean(arr1)
mid = np.median(arr1)
std =np.std(arr1)

In [16]:
print('sum of all number is:',sum)
print('mean is:',mean)
print('meadin of arr1 is:',mid)
print("Standard Deviation for arr1 is",std)

sum of all number is: 210
mean is: 10.5
meadin of arr1 is: 10.5
Standard Deviation for arr1 is 5.766281297335398


In [17]:
indices_gt_10 = np.where(arr1 > 10)
print("Indices of elements > 10:", indices_gt_10)

Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


In [18]:
## 2D Array

In [23]:
arr2 = np.arange(1,17).reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [26]:
transpose_arr2 = arr2.T
transpose_arr2


array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [28]:
num_col_wise = np.sum(arr2,axis=0)
num_row_wise =np.sum(arr2,axis=1)
print("sum number in arr2 coloum wise",num_col_wise)
print("sum number in arr2 row wise",num_row_wise)

sum number in arr2 coloum wise [28 32 36 40]
sum number in arr2 row wise [10 26 42 58]


In [30]:
arr3 = np.random.randint(1, 21, size=(3, 3))
arr4 = np.random.randint(1, 21, size=(3, 3))
print(arr3)
print(arr4)

[[19 13  6]
 [ 9  4  1]
 [17 12  3]]
[[10 17 12]
 [14 16  4]
 [11 14 19]]


In [32]:
add = arr3+arr4
sub =arr3 - arr4
mul= arr3 * arr4
print("addition of two array is:")
print(add)
print("substraction of two array is")
print(sub)
print("multiplacition of two array is:")
print(mul)

addition of two array is:
[[29 30 18]
 [23 20  5]
 [28 26 22]]
substraction of two array is
[[  9  -4  -6]
 [ -5 -12  -3]
 [  6  -2 -16]]
multiplacition of two array is:
[[190 221  72]
 [126  64   4]
 [187 168  57]]


In [34]:
#dot product
dot_product = np.dot(arr3,arr4)
print("dot product of two array is")
print(dot_product)

dot product of two array is
[[438 615 394]
 [157 231 143]
 [371 523 309]]


In [35]:
#reshaping and slicing
arr5 =np.arange(1,13)

arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
#reshape
reshaped_arr = arr5.reshape(4,3)
print("reshaped array")
print(reshaped_arr)

reshaped array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
